apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: recsys-prod
  namespace: infisical
spec:
  hostAPI: https://infisical.fatdataseo.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "recsys"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-machine-id
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: recsys-secrets
      secretNamespace: recsys
      creationPolicy: "Orphan"
