apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: redpanda
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp=1
            - --memory=2G
            - --reserve-memory=0M
            - --check=false
            - --node-id=0
            - --kafka-addr=internal://0.0.0.0:9092
            - --advertise-kafka-addr=internal://redpanda-0.redpanda.redpanda.svc.cluster.local:9092
          ports:
            - containerPort: 9092
            - containerPort: 9644
          volumeMounts:
            - name: redpanda-pv
              mountPath: /var/lib/redpanda
      nodeSelector:
        node-role.kubernetes.io/worker: worker
      volumes:
      - name: redpanda-pv
        persistentVolumeClaim:
          claimName: redpanda-pvc

