apiVersion: v1
kind: Secret
metadata:
  name: postgres-prod-secret
  namespace: databases
  labels:
    app: postgres-prod
type: Opaque
data:
  # TODO: заменить на реальные base64-encoded креды перед деплоем
  postgres-root-username: CHANGE_ME
  postgres-root-password: CHANGE_ME
