apiVersion: v1
kind: Service
metadata:
  name: postgres-prod
  namespace: databases
spec:
  selector:
    app: postgres-prod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgresql
  type: ClusterIP
